language: php

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL
    - php: 7.1
      env: DB=MYSQL

before_script:
  - phpenv rehash

  - composer validate
  - composer require --no-update silverstripe/recipe-cms:1.0.x-dev
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover